In [1]:
import torch
import torch.nn as nn

# 创建输入和输出数据
x = torch.tensor([[1.0], [2.0], [3.0]], requires_grad=True)
y_true = torch.tensor([[2.0], [4.0], [6.0]])

# 定义一个简单的线性层
model = nn.Linear(1, 1)

# 定义损失函数
criterion = nn.MSELoss()

# 前向传播
y_pred = model(x)

# 计算损失
loss = criterion(y_pred, y_true)

# 反向传播
loss.backward()

# 查看梯度
print(x.grad)  # 输入x的梯度（如果x是模型参数）
print(model.weight.grad)  # 模型权重的梯度

tensor([[-0.4723],
        [-0.9670],
        [-1.4618]])
tensor([[-13.7981]])


In [3]:
class TitanicSurvivalNN(nn.Module):
    def __init__(self):
        super(TitanicSurvivalNN, self).__init__()
        self.layer1 = nn.Linear(6, 128)  # First hidden layer
        self.layer2 = nn.Linear(128, 64) # Second hidden layer
        self.output_layer = nn.Linear(64, 1) # Output layer
        
        self.relu = nn.ReLU()  # ReLU activation function
        self.sigmoid = nn.Sigmoid()  # Sigmoid activation function

    def forward(self, x):
        x = self.relu(self.layer1(x))
        x = self.relu(self.layer2(x))
        x = self.sigmoid(self.output_layer(x))
        return x

In [7]:
model = TitanicSurvivalNN()
matrix = torch.rand(100, 6)
actual = torch.rand(100)

In [13]:
import torch.optim as optim

In [9]:
actual

tensor([0.6795, 0.4244, 0.4217, 0.4612, 0.4805, 0.8228, 0.1575, 0.1193, 0.3700,
        0.7836, 0.1138, 0.2493, 0.2556, 0.9132, 0.8062, 0.7775, 0.6336, 0.8163,
        0.2470, 0.0755, 0.3360, 0.9513, 0.7054, 0.3308, 0.1610, 0.5631, 0.0274,
        0.2240, 0.2363, 0.1723, 0.5034, 0.7694, 0.6236, 0.6622, 0.7891, 0.6591,
        0.9893, 0.0876, 0.4166, 0.4963, 0.5465, 0.4813, 0.7300, 0.6454, 0.6276,
        0.4429, 0.2560, 0.4776, 0.3827, 0.8614, 0.1652, 0.8732, 0.5155, 0.2584,
        0.6552, 0.8332, 0.3831, 0.7540, 0.0209, 0.4101, 0.9754, 0.2352, 0.4688,
        0.6223, 0.7337, 0.2326, 0.9671, 0.5566, 0.3124, 0.7196, 0.9695, 0.3121,
        0.5826, 0.8633, 0.2752, 0.6291, 0.3245, 0.6746, 0.8202, 0.9657, 0.6676,
        0.6445, 0.1626, 0.4210, 0.0581, 0.0824, 0.3064, 0.7968, 0.0440, 0.6904,
        0.1084, 0.6858, 0.5861, 0.3683, 0.2559, 0.2622, 0.1536, 0.8564, 0.9481,
        0.1926])

In [10]:
model.forward(matrix)  # Forward pass
loss = criterion(model(matrix), actual)  # Calculate loss
loss.backward()  # Backward pass

d:\ana\lib\site-packages\torch\nn\modules\loss.py:535: UserWarning: Using a target size (torch.Size([100])) that is different to the input size (torch.Size([100, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


tensor([[-1.7686e-05, -3.2574e-05, -3.0038e-05, -8.5839e-06, -2.2183e-05,
         -1.8472e-05],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00],
        [ 1.1856e-04,  1.1614e-04,  1.6000e-04,  1.0825e-04,  1.2995e-04,
          1.3944e-04],
        [ 5.4146e-05,  2.7639e-05,  4.3562e-05,  5.8429e-05,  3.0084e-05,
          3.5661e-05],
        [ 3.0364e-06,  9.4443e-07,  2.1870e-07,  3.6601e-06,  4.7202e-06,
          3.9948e-06],
        [ 1.3299e-04,  1.1196e-04,  1.2535e-04,  1.2587e-04,  1.2477e-04,
          1.1359e-04],
        [-7.3411e-06, -4.4311e-06, -4.8729e-06, -5.4451e-06, -8.7246e-06,
         -7.7139e-06],
        [-1.3702e-04, -1.4045e-04, -1.5624e-04, -1.2871e-04, -1.5611e-04,
         -1.5341e-04],
        [ 1.2166e-04,  1.1340e-04,  1.3952e-04,  1.0131e-04,  1.2011e-04,
          1.1623e-04],
        [-1.2972e-06, -6.7701e-06, -1.0769e-05, -1.8645e-06, -9.6866e-06,
         -7.9010e-06],
        [-4.5118e-06, -9.0372e